# Generated by Django 2.1.3 on 2018-11-14 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('player', models.IntegerField()),
                ('enemy', models.IntegerField()),
                ('level', models.IntegerField()),
                ('start', models.IntegerField()),
                ('log', models.TextField(default='')),
            ],
        ),
    ]
